config/routes.rb
Rails.application.routes.draw do
  resources :presents
  root 'presents#index'

end

app/models/present.rb
class Present < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  def index
    @presents = Present.all
  end

  def create
    Present.create(present_params)
    redirect_to presents_path
  end

  def new
    @present = Present.new
  end

  def edit
    @present = Present.find(params[:id])
  end

  def show
    @present = Present.find(params[:id])
  end

  def update
    Present.find(params[:id]).update(present_params)
    redirect_to presents_path
  end

  def destroy
    Present.find(params[:id]).destroy
    redirect_to presents_path
  end

  private
  def present_params
    params.require(:present).permit(:recipient, :contents, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SantasGrotto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='header'>
  <h1>Santa's Present Tracker</h1>
</div>
<nav>
  <img src='/Stocking.png'>
  <%= link_to('All presents', presents_path) %>
  <img src='/Stocking.png'>
  <%= link_to('New present', new_present_path) %>
</nav>
<%= yield %>

</body>
</html>

app/views/presents/edit.html.erb
<%= form_for @present do |f| %>
  <%= f.label :recipient %>
  <%= f.text_field :recipient %>
  <br>  
  <%= f.label :contents %>
  <%= f.text_field :contents %>
  <br>  
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.submit 'Update present' %>
<% end %>

app/views/presents/index.html.erb
<% for present in @presents do %>
  <div class="present">
    <img src='/Present.png'>
    <div class='label'>
      <span>To <%= present.recipient %></span>
      <span>Merry Christmas!</span>
    </div>
    <p>Contents: <%= present.contents %></p>
    <img src="<%= present.image %>">
  </div>
  <div class='buttons'>
    <%= link_to('Edit present', edit_present_path(present)) %>
    <%= button_to("Destroy present", present_path(present), method: :delete) %>
  </div>
<% end %>

app/views/presents/new.html.erb
<%= form_for @present do |f| %>
  <%= f.label :recipient %>
  <%= f.text_field :recipient %>
  <br>  
  <%= f.label :contents %>
  <%= f.text_field :contents %>
  <br>  
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.submit 'Add present' %>
<% end %>

app/views/presents/show.html.erb
<p><%= @present.recipient %> is to get: <%= @present.contents %></p>